parameters:
    innobyte_token.token.class: Innobyte\TokenBundle\Service\TokenService

services:
    innobyte_token.token:
        class: '%innobyte_token.token.class%'
        arguments:
            - ~ # will be replaced with the entity manager set in config
            - '@security.secure_random'
        lazy: true

    # shorthand name
    innobyte_token:
        alias: innobyte_token.token
